name: 'Status Check Labeling'
description: 'Label a pull request based on the results of its status checks'
author: 'Cloud Posse <hello@cloudposse.com>'
branding:
  icon: 'activity'
  color: 'blue'

inputs:
  label:
    description: "Label to add/remove (be sure to sync with labels in labeler-add.yml and labeler-remove.yml)"
    required: true
    default: "no-plan-changes"
  name-contains:
    description: "String to use to identify relevant status checks"
    required: true
    default: "spacelift"
  description-contains:
    description: "String that all relevant status checks descriptions must contain in order to apply the label"
    required: true
    default: "Plan contains no changes"
  github-token:
    description: "Token provided by the github actions runner"
    required: true
runs:
  using: "composite"
  steps:
    - name: Identify Required PR Labels
      id: identify-required-pr-labels
      shell: bash
      run: ${{ github.action_path }}/identify_required_pr_labels.sh
      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUTS_CHECK_DESCRIPTION: ${{ inputs.description-contains }}
        INPUTS_CHECK_NAME: ${{ inputs.name-contains }}

    - name: Determine Current PR Labels
      id: determine-current-pr-labels
      shell: bash
      run: ${{ github.action_path }}/determine_current_pr_labels.sh
      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        INPUTS_LABEL: ${{ inputs.label }}

#    - name: debugging
#      id: debugging
#      shell: bash
#      run: |
#        echo "pwd: $(pwd)"
#        ls -l .
#        echo "label_needed: $LABEL_NEEDED"
#        echo "label_present: $LABEL_PRESENT"
#      env:
#        LABEL_NEEDED: ${{ steps.identify-required-pr-labels.outputs.label_needed }}
#        LABEL_PRESENT: ${{ steps.determine-current-pr-labels.outputs.label_present }}
#
#        echo "github.action_path: ${{ github.action_path }}"
#        ls -l ${{ github.action_path }} || true
#        echo "GITHUB_ACTION_PATH: ${GITHUB_ACTION_PATH}"
#        ls -l ${GITHUB_ACTION_PATH} || true
#        echo "github context: ${GITHUB_CONTEXT}"
#        echo "github.context: ${{ toJSON(github) }}"
#        echo '$(printenv | grep "GITHUB")'

    - name: Add PR Label
      id: add-pr-label
      if: (steps.identify-required-pr-labels.outputs.label_needed == 1) && (steps.determine-current-pr-labels.outputs.label_present == 0)
      shell: bash
      run: ${{ github.action_path }}/add_pr_label.sh
      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LABEL: ${{ inputs.label }}

    - name: Remove PR Label
      id: remove-pr-label
      if: (steps.identify-required-pr-labels.outputs.label_needed == 0) && (steps.determine-current-pr-labels.outputs.label_present == 1)
      shell: bash
      run: ${{ github.action_path }}/remove_pr_label.sh
      env:
        GITHUB_EVENT_NUMBER: ${{ github.event.number }}
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LABEL: ${{ inputs.label }}
