name: dogfooding
on:
  check_suite:
    types: [completed]
  status:
  workflow_dispatch:
jobs:
  dogfood:
    name: dogfooding
    runs-on: ubuntu-latest
    steps:
      - name: status-check-summaries
        uses: cloudposse/github-action-pull-request-labeling@master
        with:
          label: "no-plan-changes"
          name-contains: "spacelift"
          description-contains: "Plan contains no changes"
          github-token: ${{ secrets.GITHUB_TOKEN }}

