name: test
on:
  workflow_dispatch:
    inputs:
      ref:
        description: "The fully-formed ref of the branch or tag that triggered the workflow run"
        required: false
        type: "string"
      sha:
        description: "The sha of the commit that triggered the workflow run"
        required: false
        type: "string"  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: test-action
        shell: bash
        runs: |
          echo "test"
